### ISSUE TITLE
Readme and main.dart showing different initialisation methods.

### ISSUE THREAD

**Issue by Prn-Ice** [OpenFlutter/flutter_screenutil#253]
In the example [Readme.md](https://github.com/OpenFlutter/flutter_screenutil/blob/master/example/README.md), you show initialisation before main is run.

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  //Set the fit size (fill in the screen size of the device in the design) If the design is based on the size of the iPhone6 ​​(iPhone6 ​​750*1334)
  ScreenUtil.init(designSize: Size(750, 1334));
  runApp(MyApp());
}
```

I saw this and really like this, It solves some issues I have with another plugin. I tried to implement it but `BoxContraints` is now required.

Meanwhile, in the example [main.dart](https://github.com/OpenFlutter/flutter_screenutil/blob/master/example/lib/main.dart), initialisation is done in the build function in `MyApp`.

I really like the previous method, does that still work and what should I pass as box constraints.

**Comment by lizhuoyuan** [comment]
There are two initialization methods, both of which are shown in the readme, don’t look at the readme in the example.
The `BoxContraints` required by the new initialization method is just a size, in a similar way to size.

Or just pass in Size as before, and you can also talk about the problems you want to solve.

**Comment by Prn-Ice** [comment]
Thanks a lot, I was able to fix my issue in the end. The problem was that I had a class that used `screen_util` injected using `get` before main. But I fixed that now, thanks.

**Comment by AlteredCarbonate** [comment]
This problem still presits - I'm new to Flutter and very confused.
All the examples didn't worked on the most recent Flutter & Dart Versions

```dart
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //Set the fit size (fill in the screen size of the device in the design) If the design is based on the size of the iPhone6 ​​(iPhone6 ​​750*1334)
    return ScreenUtilInit(
      designSize: Size(360, 690),
      builder: () =>
          MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Flutter_ScreenUtil',
            theme: ThemeData(
              primarySwatch: Colors.blue,
              textTheme: TextTheme(button: TextStyle(fontSize: 45.sp)),
            ),
            builder: (context, widget) {
              return MediaQuery(
                //Setting font does not change with system font size
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                // Without ! it throws errors about Null Safety
                child: widget!,
              );
            },
            home: MainScreen(),
          ),
    );
  }

```

**Comment by lizhuoyuan** [comment]
@AlteredCarbonate  
flutter version?

**Comment by AlteredCarbonate** [comment]
> @AlteredCarbonate
> flutter version?

Most recent `2.2.1 Stable`
